server:
  port: 8888
  servlet:
    context-path: /insta360Demo

# 数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 105293
    url: jdbc:mysql://localhost:3306/java_stack_study?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC


# Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mzl.insta360demo.entity
  type-enums-package: com.mzl.insta360demo.model.enums
  # MyBatis 原生支持的配置
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射
    mapUnderscoreToCamelCase: true
    # 在控制台打印SQL命令并打印执行结果
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 在控制台打印SQL命令不打印结果
  #    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  # 全局策略配置
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
      # 查询时不用判空
      select-strategy: not_empty

# RocketMQ消息队列配置
rocketmq:
  name-server: localhost:9876
  producer:
    group: test-producer-group

