server:
  port: 9999

spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    # password: 105293
    password: 88888888
    url: jdbc:mysql://localhost:3306/java_stack_study?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        # 手动确认消息
        acknowledge-mode: manual
        # 拒绝的消息不重新入队
        default-requeue-rejected: false


#  cloud:
#    stream:
#      binders:
#        # 自定义RabbitMQ绑定
#        rabbitBinder:
#          type: rabbit  #消息组件类型
#          environment:
#            spring: ${spring.rabbitmq}
#      bindings:
#        # 生产者通道
#        my_rabbitmq_test_output:
#          destination: topic_my_rabbitmq_test
#        # 消费者通道
#        my_rabbitmq_test_input:
#          group: group_my_rabbitmq_test
#          destination: topic_my_rabbitmq_test
#          maxAttempts: 3
#
#      # RabbitMQ的特殊配置
#      rabbit:
#        bindings:
#          # 消费者配置
#          my_rabbitmq_test_input:
#            consumer:
#              #手动提交ack
#              acknowledgeMode: MANUAL
#              # 消息消费次数达到 maxAttempts,之后丢到死信队列
#              autoBindDlq: true
#              # 死信的超时时间,毫秒,设置成1周
#              dlqTtl: 604800000

  #Redis服务器地址
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 5000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 2

# Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mzl.insta360demo.entity
  type-enums-package: com.mzl.insta360demo.model.enums
  # MyBatis 原生支持的配置
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射
    mapUnderscoreToCamelCase: true
    # 在控制台打印SQL命令并打印执行结果
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 在控制台打印SQL命令不打印结果
  #    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  # 全局策略配置
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
      # 查询时不用判空
      select-strategy: not_empty

# RocketMQ消息队列配置
rocketmq:
  name-server: localhost:9876
  producer:
    group: test-producer-group


